# Generated by Django 5.1.2 on 2024-11-09 06:26

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_user_is_staff_alter_user_is_superuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='raza',
            new_name='breed',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='descripcion',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='ubicacion',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='precio',
            new_name='starting_price',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='trazabilidad',
            new_name='traceability',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='kg',
            new_name='weight',
        ),
        migrations.RemoveField(
            model_name='post',
            name='sexo',
        ),
        migrations.AddField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 9, 6, 26, 21, 701505, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='post',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('Auction', 'Auction'), ('Post', 'Post')], default='Auction', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='app.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-amount'],
            },
        ),
    ]
