# Generated by Django 5.1.2 on 2024-11-09 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_post_created_at_alter_post_traceability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='lot',
            field=models.BooleanField(default=False),
        ),
    ]
