# Generated by Django 5.1.2 on 2024-11-09 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_post_lat_post_long_alter_post_lot_alter_post_sex_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='sex',
            field=models.CharField(choices=[('Macho', 'Macho'), ('Hembra', 'Hembra')], max_length=10),
        ),
    ]
