# Generated by Django 5.1.2 on 2024-11-09 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_post_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
