# Generated by Django 5.1.2 on 2024-11-11 05:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_post_phone_number_user_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='post',
            name='draft',
        ),
        migrations.RemoveField(
            model_name='post',
            name='type',
        ),
        migrations.AddField(
            model_name='bid',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bid',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='post',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('Auction', 'Subasta'), ('Post', 'Anuncio')], default='Post', max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='postimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postimage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='breed',
            field=models.CharField(choices=[('angus', 'Angus'), ('holstein', 'Holstein'), ('charolais', 'Charolais'), ('brahman', 'Brahman'), ('limousin', 'Limousin'), ('simmental', 'Simmental'), ('hereford', 'Hereford'), ('pardo_suizo', 'Pardo Suizo'), ('santa_gertrudis', 'Santa Gertrudis'), ('gyr', 'Gyr'), ('girolando', 'Girolando'), ('otro', 'Otro')], default='otro', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='lat',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='long',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Trazabilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo_chapa', models.CharField(max_length=20)),
                ('expediente', models.ImageField(blank=True, null=True, upload_to='expedientes/')),
                ('breed_M', models.CharField(blank=True, choices=[('angus', 'Angus'), ('holstein', 'Holstein'), ('charolais', 'Charolais'), ('brahman', 'Brahman'), ('limousin', 'Limousin'), ('simmental', 'Simmental'), ('hereford', 'Hereford'), ('pardo_suizo', 'Pardo Suizo'), ('santa_gertrudis', 'Santa Gertrudis'), ('gyr', 'Gyr'), ('girolando', 'Girolando'), ('otro', 'Otro')], default='otro', max_length=20, null=True)),
                ('breed_P', models.CharField(blank=True, choices=[('angus', 'Angus'), ('holstein', 'Holstein'), ('charolais', 'Charolais'), ('brahman', 'Brahman'), ('limousin', 'Limousin'), ('simmental', 'Simmental'), ('hereford', 'Hereford'), ('pardo_suizo', 'Pardo Suizo'), ('santa_gertrudis', 'Santa Gertrudis'), ('gyr', 'Gyr'), ('girolando', 'Girolando'), ('otro', 'Otro')], default='otro', max_length=20, null=True)),
                ('estado_de_salud', models.TextField(blank=True, null=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('categoria', models.ManyToManyField(blank=True, to='app.categoria')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.post')),
                ('vacunas', models.ManyToManyField(blank=True, to='app.vacuna')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InfoReproductiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha_de_nacimiento', models.DateField(blank=True, null=True)),
                ('ultimo_parto', models.DateField(blank=True, null=True)),
                ('fecha_de_prenez', models.DateField(blank=True, null=True)),
                ('fecha_de_ultimo_celo', models.DateField(blank=True, null=True)),
                ('dias_de_prenez', models.IntegerField(blank=True, default=0, null=True)),
                ('fecha_esperada_parto', models.DateField(blank=True, null=True)),
                ('produccion_leche_litros', models.IntegerField(blank=True, default=0, null=True)),
                ('trazabilidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.trazabilidad')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InfoLechera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('produccion_diaria_litros', models.IntegerField(blank=True, default=0, null=True)),
                ('dias_de_lactancia', models.IntegerField(blank=True, default=0, null=True)),
                ('trazabilidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.trazabilidad')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
