# Generated by Django 5.1.2 on 2024-11-11 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_categoria_vacuna_remove_post_draft_remove_post_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='post',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='user',
        ),
        migrations.RemoveField(
            model_name='post',
            name='end_date',
        ),
        migrations.CreateModel(
            name='Subasta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='app.post')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='bid',
            name='subasta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='app.subasta'),
            preserve_default=False,
        ),
    ]
